### ISSUE TITLE
Line count counts comments in C++

### ISSUE THREAD

**Issue by bobahop** [exercism/lines-of-code-counter#60]
I added some comments to [my C++ Leap solution](https://exercism.org/tracks/cpp/exercises/leap/solutions/bobahop) and the line count includes the comment lines. It brings a little tear to my eye, but it's low priority.

**Comment by iHiD** [comment]
@bobahop I've moved this here. If you fancy debugging, feel free, otherwise we'll wait for @ErikSchierboom to take a look :)

**Comment by ErikSchierboom** [comment]
@bobahop I think the confusing thing here is that the lines count will count all lines in the solution files, which also includes the `leap.h` file. Manually counting the lines of code in your `leap.cpp` and `leap.h` file, I get to 12 lines, which is what the website displays. Does that make sense?

**Comment by bobahop** [comment]
Ahhhh, I probably didn't notice that it was 12 LOC before I added the comments. Sorry to have wasted your time!

It's a separate thing, but  I've always been a bit bugged by ending brackets counting as a LOC. If someone doesn't format correctly they can have fewer lines of code without any substantive change.

**Comment by ErikSchierboom** [comment]
> Ahhhh, I probably didn't notice that it was 12 LOC before I added the comments. Sorry to have wasted your time!

No problem, it was a fairly straightforward thing to check (and I can see the confusion, as so few tracks use multiple solution files).

> It's a separate thing, but I've always been a bit bugged by ending brackets counting as a LOC. If someone doesn't format correctly they can have fewer lines of code without any substantive change.

Yeah I know, but as it is technically still code, I don't think there's any chance of it being changed, sorry.

**Comment by iHiD** [comment]
@bobahop In case you're not aware, we're thinly wrapping https://github.com/XAMPPRocky/tokei here btw. So if there are config settings or things in tokei that you'd like us to tweak, that's definitely feasible. But if it's not in there (and they don't want to accept a PR for it) then it's largely out of our control.

**Comment by bobahop** [comment]
Thanks, I'm gonna close this, as my original observation was based on an oversight.
